### PR TITLE
Create engtagger.rb

### PR DESCRIPTION
**Pull request by arjunmenon**
Basic example using POS tagging

### CODE REVIEW

**Comment by famished-tiger** [comment]
Hey Arjun,

Do you have any idea why the AppVeyor CI is failing?..

**Comment by arjunmenon** [comment]
Haha. Didn't have an idea on that. have always wondered why logs cant have more pride in what they have to say. :wink: 
At first i thought it could be because of the issue which i had opened. but na.
Let me check i would get to u on that

**Comment by famished-tiger** [comment]
Hi Arjun,

In the meantime, I fixed an annoying bug detected with an initial version of a parser of the Simple Regex Language... and a few minor details.
Just to let you know, when I committed version 0.5.0.8, I also got failing builds with AppVeyor CI as you did. Apparently, the AppVeyor people changed things in the meantime. The good new is that Linux build is running fine (so said Travis CI) and my local Windows version is also working fine.

**Comment by arjunmenon** [comment]
Hey
Long ago i pinged the appveyor guys. They have created a ticket, you may want to check out - https://twitter.com/ArjunMenon/status/934062283373678592
https://github.com/bundler/bundler/issues/6187

**Comment by famished-tiger** [comment]
Hi Arjun,

Nice to hear news from you. I really appreciate your initiative to call the Appveyor team.
Their tweet didn't really help us because the bundler command line syntax they proposed was already in the `appveyor.yml` file.
So I did some fiddling with the config file: I removed all allusions to `cmd` executable which I suspect to be no longer supported as is by Appveyor. 
The good news is that the latest commit and build passed successfully with the Appveyor CI.
My guess is that your branch will be OK after using the latest `appveyor.yml` file version.

Greetz.

**Comment by arjunmenon** [comment]
Heya
It seems the build passes. :relieved:  Removed the `--clean` flag. Simply ran `bundle install`.
Don't know much about appveyor builds. never used it.
Sorry if I have been on and off. Working on openhome on Tabrisjs. Bit tricky, since the platform doesn't have much support to native properties without dedicated plugins. That's why lagging.
Will make up surely.
Thanks.

**Review by famished-tiger — APPROVED** [review]

**Pull request merged**
